#!/bin/bash

### BEGIN INIT INFO
# Provides:          home-controller-ui
# Required-Start:    hostname $local_fs home-controller
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1 6
# Short-Description: /etc/home-controller-ui starts the home controller UI
# Description:       /etc/home-controller-ui starts the home controller UI
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh

APPSCRIPT=/home/pi/git/Tyler/homeControllerUI.py
LOGFILE=/home/pi/homeControllerUI.log
PIDFILE=/var/run/homeControllerUI.pid


do_start () {
	echo Starting homeControllerUI
	PID=`sudo -u pi xinit $APPSCRIPT localhost >> $LOGFILE 2>&1 & echo $!`
	if [ -z $PID ]; then
                echo Failed
        else
                echo $PID > $PIDFILE
                echo OK
        fi
}

do_status () {
        echo Checking homeControllerUI
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                echo Process dead but pidfile exists
            else
                echo Running
            fi
        else
            echo Not running
        fi
}


do_stop () {
	echo Stopping homeControllerUI...
            PID=`cat $PIDFILE`
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            echo Ok
            rm -f $PIDFILE
        else
            echo pidfile not found
        fi
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	do_stop
	;;
  status)
	do_status
	;;
  *)
	echo "Usage: home-controller-ui [start|stop|status]" >&2
	exit 3
	;;
esac

:
