#!/bin/bash

### BEGIN INIT INFO
# Provides:          home-controller
# Required-Start:    hostname $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1 6
# Short-Description: /etc/home-controller starts the home server and its UI
# Description:       /etc/home-controller starts the home server and its UI
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh

SERVERSCRIPT=/home/pi/git/Tyler/homeServer.py
LOGFILE=/var/log/homeServer.log
PIDFILE=/var/run/homeServer.pid

do_start () {
	echo Starting homeServer...
	PID=`$SERVERSCRIPT >> $LOGFILE 2>&1 & echo $!`
	if [ -z $PID ]; then
		echo Failed
	else
		echo $PID > $PIDFILE
		echo OK
	fi
}

do_status () {
	echo Checking homeServer
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                echo Process dead but pidfile exists
            else
                echo Running
            fi
        else
            echo Not running
        fi
}

do_stop () {
	echo Stopping homeServer...
            PID=`cat $PIDFILE`
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            echo Ok
            rm -f $PIDFILE
        else
            echo pidfile not found
        fi
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	do_stop
	;;
  status)
	do_status
	;;
  *)
	echo "Usage: home-controller [start|stop|status]" >&2
	exit 3
	;;
esac

:
